version: '3.4'

services:

 rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management
    ports:
     - 5673:5672
     - 15673:15672

 redis:
    container_name: redis
    hostname: redis
    image: redis/redis-stack-server:latest
    ports:
     - 6380:6379

 ingestionapi:
    image: ${DOCKER_REGISTRY-}ingestionapi
    build:
      context: .
      dockerfile: src/IngestionAPI/Dockerfile
    depends_on:
     - redis
     - rabbitmq
 
 
